source "${HOME}/.zgen/zgen.zsh"

zgen load chrissicool/zsh-256color
zgen load zsh-users/zsh-syntax-highlighting
zgen load zsh-users/zsh-autosuggestions
zgen load subnixr/minimal

MNML_OK_COLOR=9
MNML_USER_CHAR="❯"
MNML_INSERT_CHAR=""
MNML_INFOLN=()
MNML_MAGICENTER=(mnml_me_git)
MNML_PROMPT=(mnml_pyenv mnml_status mnml_keymap)

# Source colors for ls
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
if whence dircolors ~/.dircolors >/dev/null; then
  alias ls='ls --color'
else
  export CLICOLOR=1
  LSCOLORS=…
fi

alias ll="ls -Alh"

# VIM
#alias vim='nvim'
#alias ivm='vim'
#alias vm='nvim'
#alias vi='nvim'

